// Generated by gencpp from file plumbing_pub_sub_msg/Person.msg
// DO NOT EDIT!


#ifndef PLUMBING_PUB_SUB_MSG_MESSAGE_PERSON_H
#define PLUMBING_PUB_SUB_MSG_MESSAGE_PERSON_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace plumbing_pub_sub_msg
{
template <class ContainerAllocator>
struct Person_
{
  typedef Person_<ContainerAllocator> Type;

  Person_()
    : name()
    , age(0)  {
    }
  Person_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , age(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef uint16_t _age_type;
  _age_type age;





  typedef boost::shared_ptr< ::plumbing_pub_sub_msg::Person_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::plumbing_pub_sub_msg::Person_<ContainerAllocator> const> ConstPtr;

}; // struct Person_

typedef ::plumbing_pub_sub_msg::Person_<std::allocator<void> > Person;

typedef boost::shared_ptr< ::plumbing_pub_sub_msg::Person > PersonPtr;
typedef boost::shared_ptr< ::plumbing_pub_sub_msg::Person const> PersonConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::plumbing_pub_sub_msg::Person_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::plumbing_pub_sub_msg::Person_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::plumbing_pub_sub_msg::Person_<ContainerAllocator1> & lhs, const ::plumbing_pub_sub_msg::Person_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.age == rhs.age;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::plumbing_pub_sub_msg::Person_<ContainerAllocator1> & lhs, const ::plumbing_pub_sub_msg::Person_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace plumbing_pub_sub_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::plumbing_pub_sub_msg::Person_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::plumbing_pub_sub_msg::Person_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::plumbing_pub_sub_msg::Person_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::plumbing_pub_sub_msg::Person_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::plumbing_pub_sub_msg::Person_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::plumbing_pub_sub_msg::Person_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::plumbing_pub_sub_msg::Person_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7e88a18563a23cde36edcf14cef73c11";
  }

  static const char* value(const ::plumbing_pub_sub_msg::Person_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7e88a18563a23cdeULL;
  static const uint64_t static_value2 = 0x36edcf14cef73c11ULL;
};

template<class ContainerAllocator>
struct DataType< ::plumbing_pub_sub_msg::Person_<ContainerAllocator> >
{
  static const char* value()
  {
    return "plumbing_pub_sub_msg/Person";
  }

  static const char* value(const ::plumbing_pub_sub_msg::Person_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::plumbing_pub_sub_msg::Person_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"uint16 age\n"
;
  }

  static const char* value(const ::plumbing_pub_sub_msg::Person_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::plumbing_pub_sub_msg::Person_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.age);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Person_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::plumbing_pub_sub_msg::Person_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::plumbing_pub_sub_msg::Person_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "age: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.age);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLUMBING_PUB_SUB_MSG_MESSAGE_PERSON_H
